// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `ConfigureDnsSettings` method.
public struct ConfigureDnsSettingsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the `Registration` whose DNS settings are being updated,
  /// in the format `projects/*/locations/*/registrations/*`.
  public var registration: Swift.String = Swift.String()

  /// Fields of the `DnsSettings` to update.
  public var dnsSettings: DnsSettings? = nil

  /// Required. The field mask describing which fields to update as a comma-separated list.
  /// For example, if only the name servers are being updated for an existing
  /// Custom DNS configuration, the `update_mask` is
  /// `"custom_dns.name_servers"`.
  ///
  /// When changing the DNS provider from one type to another, pass the new
  /// provider's field name as part of the field mask. For example, when changing
  /// from a Google Domains DNS configuration to a Custom DNS configuration, the
  /// `update_mask` is `"custom_dns"`. //
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Validate the request without actually updating the DNS settings.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ConfigureDnsSettingsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigureDnsSettingsRequest().with { $0.registration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.ConfigureDnsSettingsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
