// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `ConfigureContactSettings` method.
public struct ConfigureContactSettingsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the `Registration` whose contact settings are being updated,
  /// in the format `projects/*/locations/*/registrations/*`.
  public var registration: Swift.String = Swift.String()

  /// Fields of the `ContactSettings` to update.
  public var contactSettings: ContactSettings? = nil

  /// Required. The field mask describing which fields to update as a comma-separated list.
  /// For example, if only the registrant contact is being updated, the
  /// `update_mask` is `"registrant_contact"`.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// The list of contact notices that the caller acknowledges. The notices
  /// needed here depend on the values specified in `contact_settings`.
  public var contactNotices: [ContactNotice] = []

  /// Validate the request without actually updating the contact settings.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ConfigureContactSettingsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigureContactSettingsRequest().with { $0.registration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.ConfigureContactSettingsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
