// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Defines the contact information associated with a `Registration`.
///
/// [ICANN](https://icann.org/) requires all domain names to have associated
/// contact information. The `registrant_contact` is considered the
/// domain's legal owner, and often the other contacts are identical.
public struct ContactSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Privacy setting for the contacts associated with the `Registration`.
  public var privacy: ContactPrivacy = ContactPrivacy()

  /// Required. The registrant contact for the `Registration`.
  ///
  /// *Caution: Anyone with access to this email address, phone number,
  /// and/or postal address can take control of the domain.*
  ///
  /// *Warning: For new `Registration`s, the registrant receives an email
  /// confirmation that they must complete within 15 days to avoid domain
  /// suspension.*
  public var registrantContact: ContactSettings.Contact? = nil

  /// Required. The administrative contact for the `Registration`.
  public var adminContact: ContactSettings.Contact? = nil

  /// Required. The technical contact for the `Registration`.
  public var technicalContact: ContactSettings.Contact? = nil

  /// Initialize a new instance of `ContactSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContactSettings().with { $0.privacy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details required for a contact associated with a `Registration`.
  public struct Contact: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Postal address of the contact.
    public var postalAddress: GoogleType.PostalAddress? = nil

    /// Required. Email address of the contact.
    public var email: Swift.String = Swift.String()

    /// Required. Phone number of the contact in international format. For example,
    /// `"+1-800-555-0123"`.
    public var phoneNumber: Swift.String = Swift.String()

    /// Fax number of the contact in international format. For example,
    /// `"+1-800-555-0123"`.
    public var faxNumber: Swift.String = Swift.String()

    /// Initialize a new instance of `Contact`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Contact().with { $0.postalAddress = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.domains.v1.ContactSettings.Contact"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.ContactSettings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
