// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleType
import GoogleWKT
import GoogleGax

extension Clients {
  protocol DomainsStub: Sendable {
    func searchDomains(
      request: SearchDomainsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.SearchDomainsResponse

    func retrieveRegisterParameters(
      request: RetrieveRegisterParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.RetrieveRegisterParametersResponse

    func registerDomain(
      request: RegisterDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func retrieveTransferParameters(
      request: RetrieveTransferParametersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.RetrieveTransferParametersResponse

    func transferDomain(
      request: TransferDomainRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listRegistrations(
      request: ListRegistrationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.ListRegistrationsResponse

    func getRegistration(
      request: GetRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.Registration

    func updateRegistration(
      request: UpdateRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func configureManagementSettings(
      request: ConfigureManagementSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func configureDnsSettings(
      request: ConfigureDnsSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func configureContactSettings(
      request: ConfigureContactSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func exportRegistration(
      request: ExportRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteRegistration(
      request: DeleteRegistrationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func retrieveAuthorizationCode(
      request: RetrieveAuthorizationCodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.AuthorizationCode

    func resetAuthorizationCode(
      request: ResetAuthorizationCodeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDomainsV1.AuthorizationCode

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
