// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Parameters required to register a new domain.
public struct RegisterParameters: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The domain name. Unicode domain names are expressed in Punycode format.
  public var domainName: Swift.String = Swift.String()

  /// Indicates whether the domain is available for registration. This value is
  /// accurate when obtained by calling `RetrieveRegisterParameters`, but is
  /// approximate when obtained by calling `SearchDomains`.
  public var availability: RegisterParameters.Availability = RegisterParameters.Availability()

  /// Contact privacy options that the domain supports.
  public var supportedPrivacy: [ContactPrivacy] = []

  /// Notices about special properties of the domain.
  public var domainNotices: [DomainNotice] = []

  /// Price to register or renew the domain for one year.
  public var yearlyPrice: GoogleType.Money? = nil

  /// Initialize a new instance of `RegisterParameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RegisterParameters().with { $0.domainName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible availability states of a domain name.
  public enum Availability: Codable, Equatable, Sendable {
    /// The availability is unspecified.
    case unspecified
    /// The domain is available for registration.
    case available
    /// The domain is not available for registration. Generally this means it is
    /// already registered to another party.
    case unavailable
    /// The domain is not currently supported by Cloud Domains, but may
    /// be available elsewhere.
    case unsupported
    /// Cloud Domains is unable to determine domain availability, generally
    /// due to system maintenance at the domain name registry.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .available: return 1
      case .unavailable: return 2
      case .unsupported: return 3
      case .unknown: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "AVAILABILITY_UNSPECIFIED"
      case .available: return "AVAILABLE"
      case .unavailable: return "UNAVAILABLE"
      case .unsupported: return "UNSUPPORTED"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Availability/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "AVAILABILITY_UNSPECIFIED": self = .unspecified
      case "AVAILABLE": self = .available
      case "UNAVAILABLE": self = .unavailable
      case "UNSUPPORTED": self = .unsupported
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Availability/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .available
      case 2: self = .unavailable
      case 3: self = .unsupported
      case 4: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .available: return try container.encode(1)
      case .unavailable: return try container.encode(2)
      case .unsupported: return try container.encode(3)
      case .unknown: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.domains.v1.RegisterParameters"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
